# Generated by Django 4.2.16 on 2024-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'Common User'), ('anonymous', 'Guest')], default='anonymous', max_length=10),
        ),
    ]
