# Generated by Django 5.1.1 on 2024-11-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('users', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_assignments',
            field=models.ManyToManyField(related_name='completed_by', to='assignments.assignment'),
        ),
    ]
