# Generated by Django 5.1.1 on 2024-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                default=None,
                help_text="Detailed description of the course content and objectives",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="privacy",
            field=models.BooleanField(
                choices=[(True, "Private"), (False, "Public")],
                default=None,
                help_text="Specify if the course is private or public",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("full_name", "description"),
                name="unique_course_with_description",
            ),
        ),
    ]
