# Generated by Django 4.2.16 on 2024-12-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_creator_course_enrolled_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Detailed description of the course content and objectives', max_length=1000, null=True),
        ),
    ]
