# Generated by Django 5.1.1 on 2024-11-07 20:34

import assignments.storages
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('file_upload', models.FileField(blank=True, null=True, storage=assignments.storages.AssignmentStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
