# Generated by Django 4.2.16 on 2024-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
    ]
