# Generated by Django 5.1.1 on 2024-12-01 22:42

import assignments.storages
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_file_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, storage=assignments.storages.AssignmentStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AssignmentFile',
        ),
    ]
