# Generated by Django 5.1.1 on 2024-12-01 22:51

import assignments.storages
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_file_description_assignment_file_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file_description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file_title',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file_upload',
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=assignments.storages.AssignmentStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg'])])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment')),
            ],
        ),
    ]
