# Generated by Django 5.1.1 on 2024-12-01 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_assignment_file_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
