# Generated by Django 5.1.1 on 2024-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assignment_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
    ]
